### ISSUE TITLE
Release version compatible with Python 3.11

### ISSUE THREAD

**Issue by wiget** [aws/aws-lambda-python-runtime-interface-client#106]
The code on the default branch is already supporting Python 3.11, but the latest released version support only Python <= 3.9. Releasing the new package to PyPI will help people discover that this library already supports newer Python versions.

**Comment by wiget** [comment]
I see that the new version landed on PyPI: https://pypi.org/project/awslambdaric/2.0.5/

Thanks.

**Comment by briensea** [comment]
Released in [2.0.5](https://github.com/aws/aws-lambda-python-runtime-interface-client/releases/tag/2.0.5).
