### ISSUE TITLE
Wolfi OS and installation fails.

### ISSUE THREAD

**Issue by mahadevan-karthi-dwp** [aws/aws-lambda-python-runtime-interface-client#134]
I'm trying to use this inside wolfi OS https://github.com/wolfi-dev/os/tree/main 
However, I could not make this work since the setup fails here

`/home/aws-lambda-python-runtime-interface-client-2.0.10 # python setup.py 
*** Do not use buildconf. Instead, just use: autoreconf -fi
Can't exec "libtoolize": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 318.
autoreconf: error: libtoolize failed with exit status: 2
Traceback (most recent call last):
  File "/home/aws-lambda-python-runtime-interface-client-2.0.10/setup.py", line 98, in <module>
    ext_modules=get_runtime_client_extension(),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aws-lambda-python-runtime-interface-client-2.0.10/setup.py", line 46, in get_runtime_client_extension
    extra_link_args=get_curl_extra_linker_flags(),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aws-lambda-python-runtime-interface-client-2.0.10/setup.py", line 19, in get_curl_extra_linker_flags
    check_call(["./scripts/preinstall.sh"])
  File "/usr/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./scripts/preinstall.sh']' returned non-zero exit status 2.
`

is there any debugging options available to see whats missing the host OS ? 
what that method trying to find please ? 

Also should I use autoconf ? 

thanks much

**Comment by mahadevan-karthi-dwp** [comment]
I got little further and now error seems like 



/ # pip install aws-lambda-python-runtime-interface-client-2.0.10.tar.gz 
Processing /aws-lambda-python-runtime-interface-client-2.0.10.tar.gz
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [68 lines of output]
      *** Do not use buildconf. Instead, just use: autoreconf -fi
      libtoolize: putting auxiliary files in '.'.
      libtoolize: copying file './ltmain.sh'
      libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
      libtoolize: copying file 'm4/libtool.m4'
      libtoolize: copying file 'm4/ltoptions.m4'
      libtoolize: copying file 'm4/ltsugar.m4'
      libtoolize: copying file 'm4/ltversion.m4'
      libtoolize: copying file 'm4/lt~obsolete.m4'
      libtoolize: Remember to add 'LT_INIT' to configure.ac.
      configure.ac:120: installing './compile'
      configure.ac:125: installing './missing'
      docs/examples/Makefile.am: installing './depcomp'
      checking whether to enable maintainer-specific portions of Makefiles... no
      checking whether make supports nested variables... yes
      checking whether to enable debug build options... no
      checking whether to enable compiler optimizer... (assumed) yes
      checking whether to enable strict compiler warnings... no
      checking whether to enable compiler warnings as errors... no
      checking whether to enable curl debug memory tracking... no
      checking whether to enable hiding of library internal symbols... yes
      checking whether to enable c-ares for DNS lookups... no
      checking whether to disable dependency on -lrt... (assumed no)
      checking whether to enable ECH support... no
      checking for path separator... :
      checking for sed... /bin/sed
      checking for grep... /bin/grep
      checking for egrep... /bin/grep -E
      checking for ar... /usr/bin/ar
      checking for a BSD-compatible install... /usr/bin/install -c
      checking for gcc... gcc
      checking whether the C compiler works... yes
      checking for C compiler default output file name... a.out
      checking for suffix of executables...
      checking whether we are cross compiling... no
      checking for suffix of object files... o
      checking whether the compiler supports GNU C... yes
      checking whether gcc accepts -g... yes
      checking for gcc option to enable C11 features... none needed
      checking whether gcc understands -c and -o together... yes
      checking how to run the C preprocessor... gcc -E
      checking for a sed that does not truncate output... (cached) /bin/sed
      checking for code coverage support... no
      checking whether build environment is sane... yes
      checking for a race-free mkdir -p... /bin/mkdir -p
      checking for gawk... no
      checking for mawk... no
      checking for nawk... no
      checking for awk... awk
      checking whether make sets $(MAKE)... yes
      checking whether make supports the include directive... yes (GNU style)
      checking dependency style of gcc... gcc3
      checking curl version... 7.83.1
      ./configure: line 6673: syntax error: unexpected ";;" (expecting "fi")
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-4vaebcfx/setup.py", line 98, in <module>
          ext_modules=get_runtime_client_extension(),
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-req-build-4vaebcfx/setup.py", line 46, in get_runtime_client_extension
          extra_link_args=get_curl_extra_linker_flags(),
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-req-build-4vaebcfx/setup.py", line 19, in get_curl_extra_linker_flags
          check_call(["./scripts/preinstall.sh"])
        File "/usr/lib/python3.12/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['./scripts/preinstall.sh']' returned non-zero exit status 2.
      [end of output]

**Comment by m-rph** [comment]
Hi, this seems to be the same issue as with #144. In the mean time I'd recommend using an earlier version of autoconf.
