### ISSUE TITLE
Outdated `simplejson` dependency

### ISSUE THREAD

**Issue by kpark-hrp** [aws/aws-lambda-python-runtime-interface-client#135]
We are currently pinned on `simplejson==3.17.2`.

- Doesn't have wheels for Python 3.9 and above.
- Released on July 16, 2020. Making it more than 3 years old.

I think it's time for an upgrade, don't you think? This is keeping us stuck in Python 3.8

**Comment by kpark-hrp** [comment]
@briensea @alex-pewpew @pushkarchawda @tgsong for visibility

**Comment by mahadevan-karthi-dwp** [comment]
I vote for this. Need to upgrade simplejson.  please if we know whats blocking the upgrade, willing to contribute

**Comment by briensea** [comment]
Fixed in [2.0.11](https://github.com/aws/aws-lambda-python-runtime-interface-client/releases/tag/2.0.11).
