### ISSUE TITLE
relax requirement on exact version of simplejson

### ISSUE THREAD

**Issue by thomasdziedzic-calmwave** [aws/aws-lambda-python-runtime-interface-client#147]
This strict requirement makes it impossible to bump simplejson to another major version of simplejson like 3.19.
Is there a reason why this is pinned on an exact minor version of simplejson rather than using something like >= 3.18.4?

relevant file https://github.com/aws/aws-lambda-python-runtime-interface-client/blob/main/requirements/base.txt

**Comment by m-rph** [comment]
Hi,
Afaik this will be relaxed once we migrate to a more modern way to manage the package via `pyproject.toml`. This is in the works.
