### ISSUE TITLE
test vs tests (singular/plural)

### ISSUE THREAD

**Issue by wagdav** [aws/aws-lambda-python-runtime-interface-client#20]
The tests of this package are located under the `test` (singular) directory. The project's setup.py, however contains the line:
```
  test_suite="tests",
```
using plural form.

This makes the command: `python setup.py test` fail.

The fix could be either:
1) Rename the directory test → tests
2) Fix the names in setup.py (The `packages` directive also uses the plural form)

I'm happy to submit a PR with the preferred solution. My personal preference would be 1).

**Comment by carlzogh** [comment]
Thanks for reporting this @wagdav - and good catch! Yes please, feel free to contribute this fix in a PR (also making sure that all appropriate references to the `test` directory are updated, of course)

**Comment by wagdav** [comment]
@carlzogh I opene PR #21 as discussed, please take a look. Thanks.
