### ISSUE TITLE
LAMBDA_RUNTIME Failed to get next invocation. No Response from endpoint on custom image

### ISSUE THREAD

**Issue by chand1012** [aws/aws-lambda-python-runtime-interface-client#30]
I am working on testing a custom Lambda Docker image locally. The function works great when its being ran on AWS, but my team and I need local testing and to be able to test the image using CI. Here is the entire error output I am getting.

```
Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.8/runpy.py", line 194, in _run_module_as_main
[ERROR] [1620144999666] LAMBDA_RUNTIME Failed to get next invocation. No Response from endpoint
    return _run_code(code, main_globals, None,
  File "/opt/bitnami/python/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/bitnami/python/lib/python3.8/site-packages/awslambdaric/__main__.py", line 21, in <module>
    main(sys.argv)
  File "/opt/bitnami/python/lib/python3.8/site-packages/awslambdaric/__main__.py", line 17, in main
    bootstrap.run(app_root, handler, lambda_runtime_api_addr)
  File "/opt/bitnami/python/lib/python3.8/site-packages/awslambdaric/bootstrap.py", line 416, in run
    event_request = lambda_runtime_client.wait_next_invocation()
  File "/opt/bitnami/python/lib/python3.8/site-packages/awslambdaric/lambda_runtime_client.py", line 76, in wait_next_invocation
    response_body, headers = runtime_client.next()
RuntimeError: Failed to get next
Executing 'main.handler' in function directory '/'
```

Here is the Dockerfile.

```Dockerfile
FROM public.ecr.aws/bitnami/python:3.8-prod

RUN apt-get update && apt-get install --no-install-recommends -y build-essential ffmpeg \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY . .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install awslambdaric

RUN apt-get purge build-essential -y && apt-get autoremove -y

WORKDIR /
ENTRYPOINT [ "python", "-m", "awslambdaric" ]
CMD ["main.handler"]
```

Here are the commands I am using to build and run the container.
```bash
$ docker build . -t downloader-lambda:latest
$ docker run -p 9000:8080 -e AWS_LAMBDA_RUNTIME_API="python3.8" -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e AWS_LAMBDA_FUNCTION_NAME="downloader" downloader-lambda:latest
```

The post I was using for reference on how to do this can be found [here](https://github.com/aws/aws-sam-cli/issues/2461#issuecomment-745635036). Most of our other lambdas aren't in containers so SAM can be used for testing, but we have a few that need to be tested locally that are containerized. Any help would be appreciated!

**Comment by GZaccaroni** [comment]
Same error!

**Comment by carlzogh** [comment]
Hey @chand1012 and @GZaccaroni - I believe you are referring to local testing of the RIC not working and this would be because of a missing Runtime API Server when you're trying to run the function. For local testing scenarios, I'd recommend having a look at the AWS Documentation on [Testing Lambda container images locally](https://docs.aws.amazon.com/lambda/latest/dg/images-test.html) with the [Runtime Interface Emulator](https://github.com/aws/aws-lambda-runtime-interface-emulator).

Does the image run successfully when invoked within Lambda?

**Comment by GZaccaroni** [comment]
Thank you @carlzogh , I solved by adding RIE following that tutorial https://docs.aws.amazon.com/lambda/latest/dg/images-test.html !

**Comment by gatesyp** [comment]
Worked for me too!

**Comment by luckyabsoluter** [comment]
https://docs.aws.amazon.com/lambda/latest/dg/python-image.html#python-image-clients
->
Using an alternative base image with the runtime interface client
->
(Optional) Test the image locally
->
From your project directory, run the following command to download the runtime interface emulator (x86-64 architecture) from GitHub and install it on your local machine.
```bash
mkdir -p ~/.aws-lambda-rie && \
    curl -Lo ~/.aws-lambda-rie/aws-lambda-rie https://github.com/aws/aws-lambda-runtime-interface-emulator/releases/latest/download/aws-lambda-rie && \
    chmod +x ~/.aws-lambda-rie/aws-lambda-rie
```
->
Start the Docker image with the docker run command. Note the following:
```bash
docker run --platform linux/amd64 -d -v ~/.aws-lambda-rie:/aws-lambda -p 9000:8080 \
    --entrypoint /aws-lambda/aws-lambda-rie \
    docker-image:test \
        /usr/local/bin/python -m awslambdaric lambda_function.handler
```
->
Post an event to the local endpoint.
```bash
curl "http://localhost:9000/2015-03-31/functions/function/invocations" -d '{}'
```
