### ISSUE TITLE
Question do lambda support external request via IPv6 ? 

### ISSUE THREAD

**Issue by tyjaon** [aws/aws-lambda-python-runtime-interface-client#49]
Hello I have a question it's possible to send external http request via IPv6 address  from lambda to external service outside of AWS, because I'm currently receiving error 
```
 OSError: [Errno 97] Address family not supported by protocol
```

I have tried to put my lambda function outside of the VPC the effect is the same and I also have tried to put in the private subnet(with IPv6 enabled)  with NAT configured to support IPv6 routing and effect is still the same. I would be grateful for some advice.

**Comment by reku47** [comment]
I have the same problem

**Comment by maciejbial** [comment]
Please respond to this problem, I am dealing with same issue

**Comment by carlzogh** [comment]
Hey all, thanks for reaching out - unfortunately IPv6 is not currently supported in Lambda.

**Comment by tyjaon** [comment]
@carlzogh ok thank you for information.
