### ISSUE TITLE
What happens when an AWS Lambda times out?

### ISSUE THREAD

**Issue by Arvintian** [aws/aws-lambda-python-runtime-interface-client#63]
I want to know what happens when an lambda timeout? Is like kill stop the being executed python function? whick line code show me the kill action?

**Comment by m-rph** [comment]
Hi, I am adding this comment for posterity and in case anyone finds this issue.

Lambda invokes your function in an execution environment, which provides a secure and isolated runtime environment. The execution environment manages the resources required to run your function. The execution environment also provides lifecycle support for the function's runtime and any [external extensions](https://docs.aws.amazon.com/lambda/latest/dg/lambda-extensions.html) associated with your function.

The function's runtime communicates with Lambda using the [Runtime API](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-api.html). Extensions communicate with Lambda using the [Extensions API](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-extensions-api.html). Extensions can also receive log messages and other telemetry from the function by using the [Telemetry API](https://docs.aws.amazon.com/lambda/latest/dg/telemetry-api.html).

This package implements the Runtime API.

We have the following LifeCycle.

![image](https://github.com/aws/aws-lambda-python-runtime-interface-client/assets/52372765/3a6fe396-3004-4591-a26e-56d6f615007a)

Each phase starts with an event that Lambda sends to the runtime and to all registered extensions. The runtime and each extension indicate completion by sending a `Next` API request to the execution environment. Lambda freezes the execution environment when the runtime and each extension have completed and there are no pending events.

## Shutting down

When Lambda is about to shut down the runtime (this package + your code), it sends a Shutdown event to each registered external extension. Extensions can use this time for final cleanup tasks. The Shutdown event is a response to a Next API request.

Duration: The entire Shutdown phase is capped at 2 seconds. If the runtime (this package) or any extension does not respond, Lambda terminates it via a signal (SIGKILL).
