### ISSUE TITLE
Missing ARM wheels for 2.0.1

### ISSUE THREAD

**Issue by tomkins** [aws/aws-lambda-python-runtime-interface-client#66]
I'm currently trying to install this into a minimal Docker container without build tools, which fails. Looking at:

Version 2.0.0: https://pypi.org/project/awslambdaric/2.0.0/#files
Version 2.0.1: https://pypi.org/project/awslambdaric/2.0.1/#files

Version 2.0.0 had aarch64 wheels, however 2.0.1 only has x86_64 wheels - making it a bit trickier to install.

**Comment by kapilt** [comment]
pinning version to 2.0.0 works around.. but getting a consistent aarch 64 build as part of the release process

**Comment by keshayad** [comment]
Thanks for raising it, the aarch64 wheels have been published.
Version 2.0.1: https://pypi.org/project/awslambdaric/2.0.1/#files

Closing the issue, sorry for the inconvenience.
