### ISSUE TITLE
Support Python 3.10

### ISSUE THREAD

**Issue by orf** [aws/aws-lambda-python-runtime-interface-client#85]
Hey,
It would be good to support Python 3.10.

What would need to be done for this to be supported?

**Comment by davido-nw** [comment]
I should note that general Lambda support for Python 3.10 was announced only less than a month ago: https://aws.amazon.com/about-aws/whats-new/2023/04/aws-lambda-python-3-10/

I would hope too that this should be on the radar soon.

**Comment by briensea** [comment]
Released in [2.0.5](https://github.com/aws/aws-lambda-python-runtime-interface-client/releases/tag/2.0.5) and available on [PyPi](https://pypi.org/project/awslambdaric/2.0.5/).
